base_url = "https://jsfkit.github.io"
title = "JSFKit"
description = "Open-source TypeScript packages for reading, writing, and working with spreadsheets"

[markdown]
smart_punctuation = true

[markdown.highlighting]
theme = "catppuccin-mocha"
error_on_missing_language = true
